Building and deploying
udacity/cloud-developer pull request #409
Opened 2022-06-08 21:41 UTC by ashioyajotham

2022-06-10 09:38 UTC, Inventrohyder requested changes

2022-06-10 09:38 UTC, Inventrohyder commented on course-02/exercises/udacity-c2-basic-server/src/server.ts
> +    res.status(200).send("Welcome to the Coud!");
This should remain as Cloud

2022-06-10 09:38 UTC, Inventrohyder commented on course-02/exercises/udacity-c2-basic-server/src/server.ts
> +  app.get("/cars/:id", (req: Request, res: Response) => {
Most of the changes in this file were meant as an exercise, therefore, if you need to commit, do so in your personal repo.

You can fork this repo or you can clone and push to your own.

2022-06-10 09:38 UTC, Inventrohyder commented on course-02/exercises/udacity-c2-restapi/src/config/config.ts
>      "dialect": "postgres",
These changes are mostly specific to your deployment on the cloud.

The blanks are helpful to other students to know that they have to fill them out for their own deployments

2022-06-10 09:38 UTC, Inventrohyder commented on course-02/exercises/udacity-c2-restapi/src/controllers/v0/users/routes/auth.router.ts
> +    const newUser = await User.build({
Is there a specific reason to use the `.build` syntax?


Or is it from the package upgrades?

2022-06-16 13:30 UTC, UAnjali commented
Hi,
This PR contains your personal work that cannot be added to Udacity's repository (starter-code). 
Although, feel free to suggest an update to the starter code. 
Happy Learning
Udacity

2022-06-16 13:30 UTC, closed without merging